/**
 * AGENTS.md format converter
 * Generates a universal AGENTS.md file compatible with the Agentic AI Foundation spec
 */

import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import type { ParsedRule } from './parser.js';

const NEVER_SECTION_START = '<!-- NEVER-RULES-START -->';
const NEVER_SECTION_END = '<!-- NEVER-RULES-END -->';

/**
 * Generate AGENTS.md content from rules
 */
export function generateAgentsContent(rules: ParsedRule[]): string {
    const sections: string[] = [];

    // Group rules by their category
    const groupedRules = new Map<string, ParsedRule[]>();

    for (const rule of rules) {
        const groupName = rule.frontmatter.name;
        if (!groupedRules.has(groupName)) {
            groupedRules.set(groupName, []);
        }
        groupedRules.get(groupName)!.push(rule);
    }

    // Generate content for each group
    for (const [groupName, groupRules] of groupedRules) {
        sections.push(`### ${groupName}\n`);
        sections.push(`> ${groupRules[0]?.frontmatter.description || 'No description'}\n`);

        for (const rule of groupRules) {
            for (const neverRule of rule.rules) {
                sections.push(`- ${neverRule}`);
            }
        }

        sections.push(''); // Add blank line between sections
    }

    return sections.join('\n');
}

/**
 * Generate the full AGENTS.md file content
 */
export function generateAgentsFile(rules: ParsedRule[]): string {
    const rulesContent = generateAgentsContent(rules);
    const timestamp = new Date().toISOString().split('T')[0];

    return `# AGENTS.md

This file provides guidance and constraints for AI coding agents working on this project.
It follows the [Agentic AI Foundation](https://aaif.io) specification.

## Overview

This project uses the [Never](https://github.com/mohitmishra786/never) constraint system to define
rules that AI agents should follow. These rules help maintain code quality, security, and consistency.

## Last Updated

${timestamp}

${NEVER_SECTION_START}

## Constraints

The following "Never" rules apply to all AI agents working on this codebase:

${rulesContent}
${NEVER_SECTION_END}

## Additional Guidelines

For project-specific guidelines not covered by the Never rules above, add them below.

---

*This file is partially auto-generated by Never CLI. Manual edits outside the marked sections will be preserved.*
`;
}

/**
 * Replace content between markers using indexOf for robust handling.
 * Validates marker positions to handle edge cases properly.
 */
function replaceMarkerSection(
    existingContent: string,
    rulesContent: string,
    startMarker: string,
    endMarker: string
): string | null {
    const startIndex = existingContent.indexOf(startMarker);
    const endIndex = existingContent.indexOf(endMarker);

    // Validate marker positions
    if (startIndex < 0 || endIndex < 0 || endIndex <= startIndex) {
        return null;
    }

    const beforeMarker = existingContent.slice(0, startIndex);
    const afterMarker = existingContent.slice(endIndex + endMarker.length);

    return `${beforeMarker}${startMarker}

## Constraints

The following "Never" rules apply to all AI agents working on this codebase:

${rulesContent}
${endMarker}${afterMarker}`;
}

/**
 * Update existing AGENTS.md or create new one
 */
export function updateAgentsFile(
    projectPath: string,
    rules: ParsedRule[],
    dryRun: boolean = false
): string {
    const agentsPath = join(projectPath, 'AGENTS.md');
    const rulesContent = generateAgentsContent(rules);
    let finalContent: string;

    if (existsSync(agentsPath)) {
        // Read existing file
        const existingContent = readFileSync(agentsPath, 'utf-8');

        // Try to replace the section between markers
        const replaced = replaceMarkerSection(
            existingContent,
            rulesContent,
            NEVER_SECTION_START,
            NEVER_SECTION_END
        );

        if (replaced !== null) {
            finalContent = replaced;
        } else {
            // Append our section to the end
            finalContent = `${existingContent.trim()}

---

${NEVER_SECTION_START}

## Never Constraints

${rulesContent}
${NEVER_SECTION_END}
`;
        }
    } else {
        // Create new file
        finalContent = generateAgentsFile(rules);
    }

    if (!dryRun) {
        writeFileSync(agentsPath, finalContent, 'utf-8');
    }

    return agentsPath;
}
